//! This file is @generated by surplus-test. Do not edit directly.

#[test]
fn r#div() {
    const SOURCE: &str = include_str!("tests/div.jsx");
    const COMPILED: &str = include_str!("tests/div.compiled.js");
    let result = surplus_cli::run(
            SOURCE.to_string(),
            &surplus_cli::Args {
                entry_point: None,
                output: None,
                typescript: false,
                warnings_as_errors: false,
                generate_sourcemaps: false,
                import_sjs: "@surplus/s".to_string(),
                no_minify: true,
            },
        )
        .expect("fatal error during compilation");
    let compiled = format!(
        "{}\n\n{}", "//! This file is @generated by surplus-test. Do not edit directly.",
        result.code
    );
    assert!(result.errors.is_empty(), "compilation errors: {:?}", result.errors);
    pretty_assertions::assert_str_eq!(
        COMPILED, compiled, "compiled output does not match expected output"
    );
}
#[test]
fn r#empty() {
    const SOURCE: &str = include_str!("tests/empty.jsx");
    const COMPILED: &str = include_str!("tests/empty.compiled.js");
    let result = surplus_cli::run(
            SOURCE.to_string(),
            &surplus_cli::Args {
                entry_point: None,
                output: None,
                typescript: false,
                warnings_as_errors: false,
                generate_sourcemaps: false,
                import_sjs: "@surplus/s".to_string(),
                no_minify: true,
            },
        )
        .expect("fatal error during compilation");
    let compiled = format!(
        "{}\n\n{}", "//! This file is @generated by surplus-test. Do not edit directly.",
        result.code
    );
    assert!(result.errors.is_empty(), "compilation errors: {:?}", result.errors);
    pretty_assertions::assert_str_eq!(
        COMPILED, compiled, "compiled output does not match expected output"
    );
}
#[test]
fn r#no_jsx() {
    const SOURCE: &str = include_str!("tests/no_jsx.jsx");
    const COMPILED: &str = include_str!("tests/no_jsx.compiled.js");
    let result = surplus_cli::run(
            SOURCE.to_string(),
            &surplus_cli::Args {
                entry_point: None,
                output: None,
                typescript: false,
                warnings_as_errors: false,
                generate_sourcemaps: false,
                import_sjs: "@surplus/s".to_string(),
                no_minify: true,
            },
        )
        .expect("fatal error during compilation");
    let compiled = format!(
        "{}\n\n{}", "//! This file is @generated by surplus-test. Do not edit directly.",
        result.code
    );
    assert!(result.errors.is_empty(), "compilation errors: {:?}", result.errors);
    pretty_assertions::assert_str_eq!(
        COMPILED, compiled, "compiled output does not match expected output"
    );
}
#[test]
fn r#svg() {
    const SOURCE: &str = include_str!("tests/svg.jsx");
    const COMPILED: &str = include_str!("tests/svg.compiled.js");
    let result = surplus_cli::run(
            SOURCE.to_string(),
            &surplus_cli::Args {
                entry_point: None,
                output: None,
                typescript: false,
                warnings_as_errors: false,
                generate_sourcemaps: false,
                import_sjs: "@surplus/s".to_string(),
                no_minify: true,
            },
        )
        .expect("fatal error during compilation");
    let compiled = format!(
        "{}\n\n{}", "//! This file is @generated by surplus-test. Do not edit directly.",
        result.code
    );
    assert!(result.errors.is_empty(), "compilation errors: {:?}", result.errors);
    pretty_assertions::assert_str_eq!(
        COMPILED, compiled, "compiled output does not match expected output"
    );
}
